wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-10
epochs:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 64
momentum:
  desc: null
  value: 0.9
_wandb:
  desc: null
  value:
    python_version: 3.7.0
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697665906.604532
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.7.0
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
